### ISSUE TITLE
compile can't pass now

### ISSUE THREAD

**Issue by ironyoung** [beautypi/shadertoy-iOS-v2#21]
I compile this app in Xcode, but many shader show info just like "ERROR: 0.40: Use of undeclared identifier 'iTime'". So I changed 'iGlobalTime' into 'iTime', but this shader "Creation by Silexars" can't work successfully in my phone. Anbody know why?

**Comment by reindernijhoff** [comment]
Hi, you should compile the development branche. In this branche the iTime/iGlobalTime is fixed.
I can also run the Creation shader using the code of this branche (the version by GregRostami, Creation by Silexars is not published using 'public+api').

**Comment by ironyoung** [comment]
thank you very much!
