### ISSUE TITLE
API error on many shaders

### ISSUE THREAD

**Issue by hyperknot** [beautypi/shadertoy-iOS-v2#26]
This was the only link from the API docs, so I'm opening this issue here.

The most basic API usage, like https://www.shadertoy.com/api/v1/shaders/4s2SRt?key=rt8tWH doesn't seem to work, as it gives error: 
```
{
  "Error": "Shader not found"
}
```

Even though I've just copied the code from URL of a working shader.

Context: trying to use glslViewer/glslLoader to study ShaderToy shaders, but the importer cannot work because of the API errors: https://github.com/patriciogonzalezvivo/glslViewer/issues/93

**Comment by reindernijhoff** [comment]
I think this is because the shader is not published using the 'public+api' option.
